version: '3.9'

services:

  db:
    image: mongo:7
    container_name: mongo_db
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}

  backend:
    build:
      context: ./backend/Docker-learn-node-app-       # points to your cloned backend repo folder
    container_name: node_api
    restart: unless-stopped
    environment:
      PORT: 3000
      MONGO_URI: ${MONGO_URI}
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend/Docker-learn-react-app-       # points to your cloned frontend repo folder
      dockerfile: Dockerfile
    container_name: react_app
    restart: unless-stopped
    depends_on:
      - backend

volumes:
  mongo_data: